AiReviews/Models/Film.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AiReviews.Models
{


    // Map the model to the database; data annotation
    [Table ("FILM")]


    public class Film
    {


        [Column ("film_id")]
        // XXX: FilmId should be FilmId
        // Fix this throughout
        public int FilmId
        {
            get;
            set;
        }


        // Makes this field required when inputting
        [Required]
        // Column to grab data from
        [Column ("film_name")]
        // Changes display name
        [Display (Name = "Film Name")]
        public string FilmName
        {
            get;
            set;
        }


        [Required]
        [Column ("film_genre")]
        [Display (Name = "Genre")]
        public string FilmGenre
        {
            get;
            set;
        }


        [Required]
        [Column ("film_desc")]
        // Makes the input field span multiple lines using a textarea
        [DataType(DataType.MultilineText)]
        [Display (Name = "Description")]
        public string FilmDesc
        {
            get;
            set;
        }


        // Maps only the date, rather than the date and time
        [DataType(DataType.Date)]
        [DisplayFormat(
            // Sets the display format to use the "Typical UK Format"
            // ... even though ISO 8601 date is superior :3
            DataFormatString = "{0:dd/MM/yyyy}",
            // Provides extra UI for picking date etc. while editing
            ApplyFormatInEditMode = true
            )]
        [Column ("film_releaseDate")]
        [Display (Name = "Release Date")]
        // DateTime? ... the ? makes it a NULLable field
        public DateTime? FilmReleaseDate
        {
            get;
            set;
        }


        [Column ("film_icon")]
        [Display (Name = "Image")]
        public string FilmIcon
        {
            get;
            set;
        }

        public string FilmDescTrimmed
        {
            get
            {
                // Returns either the entire film description if under 100 chars, or returns the first 100 chars with "..." affixed to the end
                if ((FilmDesc.Length) > 100)
                {
                    return FilmDesc.Substring(0, 100) + "...";
                } else
                {
                    return FilmDesc;
                }
            }
        }
    }
}

AiReviews/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AiReviews.Models;
using AiReviews.Models.ViewModels;
using PagedList;

namespace AiReviews.Controllers
{
    public class ReviewsController : Controller
    {
        private DBContext db = new DBContext();
        public ActionResult Search(string searchFor, string searchTerm)
        {
            // Create a list for the view model to link FilmReviews and Films
            List<FilmReviewViewModel> FilmReviewList =
                new List<FilmReviewViewModel>();

            // List of review objects to cycle through and map ids
            List<Review> Reviews;

            // Populate the Reviews list by selecting all records
            // from the db context
            Reviews = db.Reviews.ToList();

            // Loop through each review in the list of data (each row)
            foreach (Review i in Reviews)
            {
                // Match the ID between Review and Films, store the result in film
                Film film = db.Films.Where(z => z.FilmId == i.FilmId).Single();

                // New DirectorFilmListViewModel object to then add to the list
                FilmReviewViewModel toAdd = new FilmReviewViewModel();

                // Get the Review and Film
                // use these to prepare what should be added
                toAdd.Review = i;
                toAdd.Film = film;

                // Add to the FilmReviewList (list of ViewModel objects)
                FilmReviewList.Add(toAdd);
            }
            
            // Depending on what user is "searching for", select only matching items based on that
            if (searchFor == "searchFilmName")
            {
                var searchables = from f in db.Films
                                  select new
                                  {
                                      id = f.FilmId,
                                      name = f.FilmName,
                                  };

                searchables = searchables.Where(n => n.name.Contains(searchTerm));

                return Json(searchables, JsonRequestBehavior.AllowGet);
            }

            if (searchFor == "searchReviewerName")
            { 
                var searchables = from f in FilmReviewList
                                  select new
                                  {
                                      id = f.Review.ReviewId,
                                      name = f.Review.ReviewReviewerName
                                  };

                searchables = searchables.Where(n => n.name.Contains(searchTerm));

                return Json(searchables, JsonRequestBehavior.AllowGet);
            }
            return View();
        }

        // GET: Reviews
        public ActionResult Index(int? page, string lastSort, string clickedSort, string currentFilterFilmName, string searchFilmName, string currentFilterReviewerName, string searchReviewerName)
        {
            // Create a list for the view model to link FilmReviews and Films
            List<FilmReviewViewModel> FilmReviewList =
                new List<FilmReviewViewModel>();

            // List of review objects to cycle through and map ids
            List<Review> Reviews;

            // Populate the Reviews list by selecting all records
            // from the db context
            Reviews = db.Reviews.ToList();

            // Loop through each review in the list of data (each row)
            foreach (Review i in Reviews)
            {
                // Match the ID between Review and Films, store the result in film
                Film film = db.Films.Where(z => z.FilmId == i.FilmId).Single();

                // New DirectorFilmListViewModel object to then add to the list
                FilmReviewViewModel toAdd = new FilmReviewViewModel();

                // Get the Review and Film
                // use these to prepare what should be added
                toAdd.Review = i;
                toAdd.Film = film;

                // Add to the FilmReviewList (list of ViewModel objects)
                FilmReviewList.Add(toAdd);
            }

            // For the ViewBag to keep a note of current sort order
            if (!String.IsNullOrEmpty(lastSort))
            {
                ViewBag.LastSort = lastSort;
            }
            // Make defualt be firstName
            else
            {
                ViewBag.LastSort = "filmName";
            }

            // If clickedSort contains something, aka an option was clicked
            if (!String.IsNullOrEmpty(clickedSort))
            {
                // If the current sort "contains" the clicked sort, aka clicked current option (regardless of if it's inverted)
                if (ViewBag.LastSort.Contains(clickedSort))
                {
                    // If it was already "inverted", trim it to not identify as inverted
                    if (ViewBag.LastSort.Contains("Inverted"))
                    {
                        ViewBag.LastSort = clickedSort;
                    }
                    // Otherwise, suffix "inverted"
                    else
                    {
                        ViewBag.LastSort = lastSort + "Inverted";
                    }
                }
                // Since the current sort didn't "contain" the clicked sort, just make it normally sorted via that type
                else
                {
                    ViewBag.LastSort = clickedSort;
                }
            }

            // Reset to page 1 if user searched, otherwise push the current params into what will be checked next
            if (searchFilmName != null)
                page = 1;
            else
                searchFilmName = currentFilterFilmName;

            if (searchReviewerName != null)
                page = 1;
            else
                searchReviewerName = currentFilterReviewerName;

           

            var filmReviewList = from f in FilmReviewList select f;

            // See films index:
            string viewBagCurrentFilmName = ViewBag.CurrentFilterFilmName;
            string viewBagCurrentReviewerName = ViewBag.CurrentFilterReviewerName;

            if (!String.IsNullOrEmpty(searchFilmName))
            {
                if (viewBagCurrentReviewerName != null)
                    filmReviewList = filmReviewList.Where(z => z.Review.ReviewReviewerName.Contains(viewBagCurrentReviewerName));
                filmReviewList = filmReviewList.Where(z => z.Film.FilmName.Contains(searchFilmName));
            }

            if (!String.IsNullOrEmpty(searchReviewerName))
            {
                if (!String.IsNullOrEmpty(viewBagCurrentFilmName))
                    filmReviewList = filmReviewList.Where(z => z.Film.FilmName.Contains(viewBagCurrentFilmName));
                filmReviewList = filmReviewList.Where(z => z.Review.ReviewReviewerName.Contains(searchReviewerName));
            }

            // Update ViewBag
            ViewBag.CurrentFilterFilmName = searchFilmName;
            ViewBag.CurrentFilterReviewerName = searchReviewerName;

            // Go over what the new sort should be and apply it
            switch (ViewBag.lastSort)
            {
                case "filmName":
                    filmReviewList = filmReviewList.OrderBy(z => z.Film.FilmName);
                    break;
                case "filmNameInverted":
                    filmReviewList = filmReviewList.OrderByDescending(z => z.Film.FilmName);
                    break;
                case "reviewerName":
                    filmReviewList = filmReviewList.OrderBy(z => z.Review.ReviewReviewerName);
                    break;
                case "reviewerNameInverted":
                    filmReviewList = filmReviewList.OrderByDescending(z => z.Review.ReviewReviewerName);
                    break;
                case "reviewRating":
                    filmReviewList = filmReviewList.OrderBy(z => z.Review.ReviewStars);
                    break;
                case "reviewRatingInverted":
                    filmReviewList = filmReviewList.OrderByDescending(z => z.Review.ReviewStars);
                    break;
                default:
                    filmReviewList = filmReviewList.OrderBy(z => z.Film.FilmName);
                    break;
            }

            // How many records per page (could also be a param...)
            int pageSize = 3;

            // If page is null: set to 1
            // otherwise: keep page value
            int pageNumber = (page ?? 1);

            // Send the updated films list to the View: Use PagedList to implement pagination,
            // and proide the pageSize
            return View(filmReviewList.ToPagedList(pageNumber, pageSize));
        }

        // GET: Reviews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            // Find the related film
            Film film = db.Films.Where(z => z.FilmId == review.FilmId).Single();
            // Create a new view model object and assign the review and film details
            FilmReviewViewModel FilmReview = new FilmReviewViewModel();
            FilmReview.Review = review;
            FilmReview.Film = film;

            // Sebd the view model to the View
            return View(FilmReview);
        }

        // GET: Reviews/Create
        public ActionResult Create(int id = 0)
        {
            // If no id sent, redirect to reviews index
            // Makes sure reviews can only be made for existing films
            if (id == 0)
            {

AiReviews/Views/Films/Create.cshtml
@model AiReviews.Models.Film

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@* Creates a form tag to submit *@
@* https://msdn.microsoft.com/en-us/library/system.web.mvc.html.formextensions.beginform(v=vs.118).aspx *@

@using (Html.BeginForm(
    "Create",
    "Films",
    null,
    FormMethod.Post,
    // Sets the encoding type
    new { enctype = "multipart/form-data" }
    ))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Film</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FilmName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilmName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FilmName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @* XXX: I don't know why "MovieID" is used here *@
            <label class="control-label col-md-2" for="MovieID">Genre</label>
            <div class="col-md-10">
                @* Mmmm ViewBags. Get the GenreList and make it a dropdown *@
                @Html.DropDownList("FilmGenre")
                @Html.ValidationMessageFor(model => model.FilmId, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
            @Html.LabelFor(model => model.FilmGenre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilmGenre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FilmGenre, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.FilmDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilmDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FilmDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilmReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilmReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FilmReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @* Default generated code *@
        @* <div class="form-group">
                @Html.LabelFor(model => model.FilmIcon, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FilmIcon, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FilmIcon, "", new { @class = "text-danger" })
                </div>
            </div> *@

        @* Simple input tag that uses a file upload *@
        <div class="form-group">
            @Html.Label("Image", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Image" name="upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AiReviews/Views/Films/Delete.cshtml
@model AiReviews.Models.Film

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Film</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FilmName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilmName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FilmGenre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilmGenre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FilmDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilmDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FilmReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilmReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FilmIcon)
        </dt>

        <dd>
            @* If FilmIcon is not null, display the image *@
            @if (Model.FilmIcon != null)
            {
                <img src="@Url.Content(Model.FilmIcon)" width="100"/>
            }
            @* @Html.DisplayFor(model => model.FilmIcon) *@
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AiReviews/Views/Films/Details.cshtml
@model AiReviews.Models.ViewModels.FilmPageViewModel

@* Old *@
@* @model AiReviews.Models.Film *@

@{
    ViewBag.Title = "Details";
}
<script type="text/javascript">
    $(document).ready(function () {

        // For each of the Star dropdowns
        $('.Stars').each(function () {
            // Get the value of the id from the hidden field next to it
            let selectId = $(this).next().val();
            // Now apply this as the selected id to the current dropdown box
            $(this).val(selectId);
        });

        // Now apply the plugin and set to readonly
        $('.Stars').barrating({
            theme: 'fontawesome-stars',
            readonly: true
        });

    });
</script>
<h2>Details</h2>

<div>
    <h4>Film</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Film.FilmName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Film.FilmName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Film.FilmGenre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Film.FilmGenre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Film.FilmDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Film.FilmDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Film.FilmReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Film.FilmReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Film.FilmIcon)
        </dt>

        <dd>
            @* If FilmIcon is not null, display the image *@
            @if (Model.Film.FilmIcon != null)
            {
                <img src="@Url.Content(Model.Film.FilmIcon)" width="100" />
            }
            @* @Html.DisplayFor(model => model.FilmIcon) *@
        </dd>

        @* Display the average review *@
        <dt>
            Rating:
            <p>(Rounded down due to Font Awesome)</p>
        </dt>

        <dd>
            <select class="Stars">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
            @* FIXME: This breaks with decimals. Either round down or get the fractal thing to work *@
            <input type="hidden" class="initialRating" value="@ViewBag.AverageReview" />

    </dl>
</div>



<p>
    @*
        Submit to
        1: Add Actor (Film) route
        Places clickable link on the page which links to the custom Route in RouteConfig.cs
        This, essentially, pre-selects the Film in the "Movie Selection" dropdown
    *@
    @Html.ActionLink("Add Director", "Create", "DirectorFilms",
        new { subName = "Film", Model.Film.FilmId }, null) |


    @Html.ActionLink("Add Actor", "Create", "ActorFilms",
        new { subName = "Film", Model.Film.FilmId }, null) |


    @* Add Review button; sends the id to the Create View for Reviews *@
    @Html.ActionLink("Add Review", "Create", "Reviews",
        new { id = Model.Film.FilmId }, null) |

    @Html.ActionLink("Edit", "Edit", new { id = Model.Film.FilmId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<hr />
<hr />

<div>
    <h4>Directors</h4>
    <hr />
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Directors.FirstOrDefault().DirectorFname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Directors.FirstOrDefault().DirectorSname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Directors.FirstOrDefault().DirectorDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Directors.FirstOrDefault().DirectorDateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Directors.FirstOrDefault().DirectorImage)
            </th>
        </tr>
        @{
            bool zeroDirectors = true;

            foreach (var director in Model.Directors)
            {
                zeroDirectors = false;
                <tr>
                    <td>
                        @Html.ActionLink(director.DirectorFname, "../Directors/Details", new { id = director.DirectorId })
                    </td>

                    <td>
                        @Html.ActionLink(director.DirectorSname, "../Directors/Details", new { id = director.DirectorId })
                    </td>

                    <td>
                        @Html.DisplayFor(model => director.DirectorDesc)
                    </td>

                    <td>
                        @Html.DisplayFor(model => director.DirectorDateOfBirth)
                    </td>

                    <td>
                        @if (director.DirectorImage != null)
                        {
                            <img src="@Url.Content(director.DirectorImage)" width="100" />
                        }
                    </td>
                </tr>
            }
            if (zeroDirectors)
            {
                <tr>No directors</tr>
            }
        }
    </table>
</div>

<hr />
<hr />

<div>
    <h4>Actors</h4>
    <hr />
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Actors.FirstOrDefault().ActorFname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Actors.FirstOrDefault().ActorSname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Actors.FirstOrDefault().ActorDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Actors.FirstOrDefault().ActorDateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Actors.FirstOrDefault().ActorImage)
            </th>
        </tr>
        @{
            bool zeroActors = true;

            foreach (var actor in Model.Actors)
            {
                zeroActors = false;
                <tr>
                    <td>
                        @Html.ActionLink(actor.ActorFname, "../Actors/Details", new { id = actor.ActorId })
                    </td>

                    <td>
                        @Html.ActionLink(actor.ActorSname, "../Actors/Details", new { id = actor.ActorId })
                    </td>

                    <td>
                        @Html.DisplayFor(model => actor.ActorDesc)
                    </td>

                    <td>
                        @Html.DisplayFor(model => actor.ActorDateOfBirth)
                    </td>

                    <td>
                        @if (actor.ActorImage != null)
                        {
                            <img src="@Url.Content(actor.ActorImage)" width="100" />
                        }
                    </td>
                </tr>
            }
            if (zeroActors)
            {
                <tr>No actors</tr>
            }
        }
    </table>
</div>

<hr />
<hr />

<div>
    <h4>Reviews</h4>
    <hr />
    @*
        For ever review:
            Display review:
                ReviewStars, ReviewReviewerName,ReviewContentTrimmed
            Display links:
                Full Review, Edit Review, All Reviews
    *@
    @{
        bool zeroReviews = true;

        foreach (var review in Model.Reviews)
        {
            zeroReviews = false;
            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => review.ReviewStars)
                </dt>

                <dd>
                    <select class="Stars">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>
                    <input type="hidden" class="initialRating" value="@review.ReviewStars" />
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => review.ReviewReviewerName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => review.ReviewReviewerName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => review.ReviewContent)
                </dt>

                <dd>
                    @Html.DisplayFor(model => review.ReviewContentTrimmed)
                </dd>
            </dl>

            @* Links for each review*@
            <p>
                @Html.ActionLink("Full Review", "Details", "Reviews", new { id = review.ReviewId }, "") |
                @Html.ActionLink("Edit Review", "Edit", "Reviews", new { id = review.ReviewId }, null) |
                @Html.ActionLink("All Reviews", "Index", "Reviews")
            </p>
        }
        if (zeroReviews)
        {
            <h5>No reviews published yet</h5>
        }
    }
</div>

AiReviews/Views/Films/Edit.cshtml
@model AiReviews.Models.Film

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm(
    "Edit",
    "Films",
    null,
    FormMethod.Post,
    // Sets the encoding type
    new { enctype = "multipart/form-data" }
    )) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Film</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.FilmId)

        <div class="form-group">
            @Html.LabelFor(model => model.FilmName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilmName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FilmName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilmGenre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilmGenre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FilmGenre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilmDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilmDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FilmDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilmReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @* Applies date edit type upon interaction, but keeps the default value for the record *@
                @Html.TextBoxFor(m => m.FilmReleaseDate, "{0:yyyy-MM-dd}", htmlAttributes: new { @type = "date" })
                @Html.ValidationMessageFor(model => model.FilmReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @* Default Generated Code *@
        @* <div class="form-group">
            @Html.LabelFor(model => model.FilmIcon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilmIcon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FilmIcon, "", new { @class = "text-danger" })
            </div>
        </div> *@

        @* Image-handling image edit *@
        <div class="form-group">
            @Html.Label("Image", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Image" name="upload"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}